// Generated by tools/par/compute-par.ts. Do not edit by hand.
//
// The mean guess count for strong play opening from house starters, over
// 300 simulated days against word lists fc66685a12af.
//
// Regenerate whenever the word lists change: PAR is derived from them, and a
// stale value leaves every total mis-centred. See docs/scoring.md.

export const GENERATED_PAR_V1 = 3.7100;
export const GENERATED_PAR_V2 = 3.9100;
export const GENERATED_PAR = GENERATED_PAR_V1;
