/**
 * Recompute `PAR` and write it into src/engine/config/par.generated.ts.
 *
 * `PAR` is the mean guess count for strong play opening from house starters.
 * Deliberately not average-human play: if par were the average result, half the
 * field would be under par on any given day and the phrase would mean nothing.
 *
 * Run this whenever the word lists change. A stale PAR leaves every total
 * mis-centred — it cancels between two players on the same day, so it never
 * makes the competition unfair, but it does make the golf framing lie.
 *
 *   npm run compute-par -- --days 300
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

import { WORD_LIST_VERSION } from '../../src/data';
import { play, puzzlesFor, rulesetFor } from './simulate';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUTPUT = resolve(HERE, '../../src/engine/config/par.generated.ts');

function parseDays(argv: readonly string[]): number {
  const flag = argv.indexOf('--days');
  if (flag < 0) return 300;
  const value = Number(argv[flag + 1]);
  if (!Number.isSafeInteger(value) || value <= 0) {
    throw new RangeError(`--days needs a positive integer, got ${argv[flag + 1]}`);
  }
  return value;
}

function main(): void {
  const days = parseDays(process.argv.slice(2));
  const ruleset = rulesetFor('normal');
  const puzzles = puzzlesFor(days);

  const distribution = new Map<number, number>();
  let totalGuesses = 0;
  let unsolved = 0;
  let bestOpenerGuesses = 0;

  const started = Date.now();
  for (const [index, puzzle] of puzzles.entries()) {
    const fromHouse = play({
      opener: puzzle.starter,
      answer: puzzle.answer,
      ruleset,
      continuation: 'strong',
    });

    totalGuesses += fromHouse.guessesUsed;
    if (!fromHouse.solved) unsolved += 1;
    distribution.set(fromHouse.guessesUsed, (distribution.get(fromHouse.guessesUsed) ?? 0) + 1);

    // Philosophy position 9 claims starter quality is worth about a tenth of a
    // guess. Measuring it here keeps that a checked fact.
    bestOpenerGuesses += play({
      opener: FIXED_STRONG_OPENER,
      answer: puzzle.answer,
      ruleset,
      continuation: 'strong',
    }).guessesUsed;

    if ((index + 1) % 25 === 0) {
      process.stdout.write(`  ${index + 1}/${days} days\r`);
    }
  }

  const par = totalGuesses / days;
  const fromFixed = bestOpenerGuesses / days;
  const elapsed = ((Date.now() - started) / 1000).toFixed(1);

  process.stdout.write('\n');
  console.log(`days simulated      ${days}`);
  console.log(`word lists          ${WORD_LIST_VERSION}`);
  console.log(`PAR (house starter) ${par.toFixed(4)}`);
  console.log(`  from ${FIXED_STRONG_OPENER.toUpperCase()}          ${fromFixed.toFixed(4)}`);
  console.log(`  starter costs     ${(par - fromFixed).toFixed(4)} guesses`);
  console.log(`unsolved            ${unsolved}`);
  console.log('distribution');
  for (const guesses of [...distribution.keys()].sort((a, b) => a - b)) {
    const count = distribution.get(guesses)!;
    console.log(`  ${guesses}: ${String(count).padStart(4)}  ${'█'.repeat(Math.round((60 * count) / days))}`);
  }
  console.log(`took                ${elapsed}s`);

  writeFileSync(OUTPUT, render(par, days), 'utf8');
  console.log(`\nwrote ${OUTPUT}`);
}

/**
 * A fixed, strong opener used only as a yardstick for what the house starter
 * costs. Not shipped, and never suggested to a player.
 */
const FIXED_STRONG_OPENER = 'slate';

function render(par: number, days: number): string {
  return `// Generated by tools/par/compute-par.ts. Do not edit by hand.
//
// The mean guess count for strong play opening from house starters, over
// ${days} simulated days against word lists ${WORD_LIST_VERSION}.
//
// Regenerate whenever the word lists change: PAR is derived from them, and a
// stale value leaves every total mis-centred. See docs/scoring.md.

export const GENERATED_PAR = ${par.toFixed(4)};
`;
}

main();
