// Generated by tools/wordlists/build.py. Do not edit by hand.
//
// Derived from the contents of all three lists. Share links carry this
// so a replay built against different lists is flagged rather than
// silently rescored against the wrong words (spec §5).
// Current lists: answers 3000, guesses 12972, starters 5000.

export const WORD_LIST_VERSION = 'fc66685a12af';
